//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebCyE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaContext : DbContext
    {
        public SistemaContext()
            : base("name=SistemaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuestionarios> cuestionarios { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<encuestas> encuestas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_respuesta> tipo_respuesta { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    
        public virtual ObjectResult<sp_ObtenerDepartamentos_Result> sp_ObtenerDepartamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerDepartamentos_Result>("sp_ObtenerDepartamentos");
        }
    
        public virtual int sp_RegistrarDepartamento(string nombre, ObjectParameter mensaje, ObjectParameter resultado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarDepartamento", nombreParameter, mensaje, resultado);
        }
    }
}
