//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebCyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.cuestionarios = new HashSet<cuestionarios>();
            this.encuestas = new HashSet<encuestas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_departamento { get; set; }
        public Nullable<int> ID_tipo_usuario { get; set; }
        public string nombres { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string genero { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<bool> restablecer { get; set; }
        public Nullable<bool> status { get; set; }
        public string nombre_usuario { get; set; }
        public string pass { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuestionarios> cuestionarios { get; set; }
        public virtual departamentos departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encuestas> encuestas { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
